project:
  type: book
  output-dir: docs
  
book:
  title: "Generative Artificial Intelligence (Gen-AI) booklet"
  author: "Ozan Evkaya"
  search: true
  cover-image: images/cover.png
  repo-url: https://github.com/oevkaya/Gen-AI-book
  repo-branch: master
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - part: Intro_GenAI.qmd
      chapters: 
        - basics.qmd
        - Glossary.qmd
        - transformers.qmd
    - part: LLMs.qmd
      chapters:
        - ChatGPT.qmd
        - Bard-Gemini.qmd
        - Claude2.qmd
        - Llama2.qmd
        - OtherLLMs.qmd
    - part: Prompting.qmd
      chapters:
        - GeneralTips.qmd
        - Strategies.qmd
    - part: AdvancedTopics.qmd
      chapters:
        - Usecases.qmd
        - LLM-apps.qmd
  appendices:
    - a1-ext-sources.qmd
    - a2-inspring.qmd
    - a3-GenAI-maths.qmd
    - a4-OtherTools.qmd
    - a5-FurtheRead.qmd 

comments:
  hypothesis: true

format:
  html: 
    theme: cosmo
    cover-image: images/GenAIbanner.png
    code-link: true


