# Preface {.unnumbered}

Although the history of AI tools is old, the potential impact of Gen-AI may be huge for various sectors. The current form of these tools has the real potential to transform the way we live and work, regardless of whether we like it or not. As a matter of fact, we started to hear various news about their potential use cases in diverse fields, including the Mayo Clinic research hospital, which tries to implement Google's medical AI chatbot, or Harvard University which announced the new version of the online Computer Science (CS50) having a new teacher bot feature. In the meantime, there are various opposite thoughts about the rise of AI-powered tools, including those who think that this is the beginning of Artificial general Intelligence (AGI) or that these tools are nowhere near as mind-blowing as they presume.

In the last year, the initial reactions from the higher education community were mixed, including certain banning intentions across different countries. Mainly, one of the main concerns has been the potential for students to use such tools to cheat and generate unauthentic works, having big impacts on their integrity, whereas we all know that this is not a new problem indeed. A more critical concern is the possibility of over-reliance on generated outputs, which hinders the capacity to think independently or detect incorrect output from Gen-AI tools. Furthermore, the use of such tools raises a number of ethical concerns, such as the propagation of bias in the generated content and the disclosure of personal information to the operating companies. As the use of Gen-AI could have a profound impact, it is becoming increasingly vital for students and faculty to comprehend the capabilities and limitations of these systems.

In the light of all of these,

## Main conventions

Throughout the booklet, some related terms will be used interchangeably such as Gen-AI, Large Language Models (LLMs) or Foundation models.

Different LLMs will be stated explicitly based on their properties. Some visual aids will be used for the general summary by citing their main source.

## Why?

After spending one year with all the breakthroughs! in Gen-AI we all both amazed and frightened by their capabilities. To some extent, as a society, once again, we saw that how quick we are for the embracement of some tools even if all other big problems still persistent. Especially, in the higher education landscape, both naysayers or yeasayers experiences certain benefits and challenges while day-by-day new tools and developments are announced. For that reason, my humble opinion is that it is better to curate related sources and materials on a unique website by knowing that this is impossible from the beginning!

## Who is this for?

All Gen-AI lovers! and people who are interested in regularly looking at certain resources are welcome aboard.

For sure, personally, I can not handle all of those so my humble dream is that you want to add comments or do some edits to the book.

## Acknowledgments

Embarking on the journey of authoring "Generative AI booklet" has been an enlightening voyage after hours spent for reading different sources. This endeavor would not have been possible without the unwavering support and intellectual generosity of many individuals and institutions.

The collaborative spirit of the open-source community has been a cornerstone in refining and augmenting the content of this booklet. I am immensely thankful to those who took the time and effort to contribute fixes and improvements.
